---
username: "josh"

# Apps and Packages
packages:
  - bat
  - btop
  - curl
  - cmake
  - dnsutils
  - htop
  - fzf
  - gettext
  - git
  - neofetch
  - ripgrep
  - tmux
  - tree
  - zsh

ubuntu_packages:
  - autoconf 
  - automake
  - cmake
  - doxygen
  - eza
  - g++
  - libfreetype6
  - libfontconfig1-dev
  - libxcb-xfixes0-dev
  - libxkbcommon-dev
  - libtool
  - libtool-bin
  - ninja-build
  - pkg-config 
  - python3
  - unzip 
  - xsel

apps:
  - notion
  - slack

mac_apps:
  - alfred
  - rectangle
