---
username: "josh"

# Apps and Packages
packages:
  - bat
  - btop
  - curl
  - cmake
  - dnsutils
  - htop
  - fzf
  - gettext
  - git
  - neofetch
  - ripgrep
  - tmux
  - tree
  - zsh


ubuntu_packages:
  - ninja-build
  - libtool
  - libtool-bin
  - autoconf 
  - automake
  - g++
  - pkg-config 
  - unzip 
  - doxygen
  - xsel

apps:
  - notion
  - slack
  - vagrant

mac_apps:
  - alfred
  - rectangle
