---
username: "josh"

# Apps and Packages
packages:
  - bash
  - bat
  - bc
  - btop
  - cmake
  - coreutils
  - curl
  - direnv
  - dnsutils
  - fzf
  - htop
  - gawk
  - gettext
  - git
  - jq
  - neofetch
  - playerctl
  - ripgrep
  - tmux
  - tree
  - zsh

ubuntu_packages:
  - autoconf
  - automake
  - build-essential
  - cmake
  - doxygen
  - g++
  - libfreetype6
  - libfontconfig1-dev
  - libreadline-dev
  - libxcb-xfixes0-dev
  - libxkbcommon-dev
  - libtool
  - libtool-bin
  - lua5.4
  - liblua5.4-dev
  - ninja-build
  - pkg-config
  - python3
  - unzip
  - xsel

apps:
  - notion
  - slack

mac_apps:
  - alfred
  - rectangle
