---
- name: Configure host.
  become: true
  hosts: all

  vars_files:
    - default.config.yml

  pre_tasks:
    - name: Set home directory for Debian
      set_fact:
        homedir: "/home/{{ username }}"
      when: ansible_os_family == "Debian"
      tags:
        - always

    - name: Set home directory for MacOS
      set_fact:
        homedir: "/Users/{{ username }}"
      when: ansible_os_family == "Darwin"
      tags:
        - always

  roles:
    - role: system
      tags: system

    - role: zsh
      tags: zsh

    - role: ssh
      tags: ssh

    - role: tmux
      tags: tmux

    - role: nvim
      tags: nvim
