---
- name: Configure host.
  hosts: all

  vars_files:
    - default.config.yml

  roles:
    - role: system
      tags: system
      become: true

    - role: zsh
      tags: zsh

    - role: ssh
      tags: ssh
      become: true

    - role: tmux
      tags: tmux

    - role: nvim
      tags: nvim
