---
- hosts: localhost
  connection: local

  roles:
    - role: system
      become: true
      tags: system
    - role: zsh
      tags: zsh
    - role: ssh
      become: true
      tags: ssh
    - role: tmux
      tags: tmux
    - role: nvim
      tags: nvim
