---
# Apps and Packages
packages:
  - curl
  - htop
  - exa
  - fzf
  - git
  - neofetch
  - neovim
  - ripgrep
  - tree
  - zsh

ubuntu_packages:
  - ninja-build
  - gettext
  - libtool
  - libtool-bin
  - autoconf 
  - automake
  - cmake
  - g++
  - pkg-config 
  - unzip 
  - doxygen

apps:
  - notion
  - slack
  - vagrant

mac_apps:
  - alfred
  - rectangle
