---
# Versions
nvim_version: "v0.7.2"

# Apps and Packages
packages:
  - htop
  - exa
  - fzf
  - git
  - neofetch
  - ripgrep
  - zsh

apps:
  - notion
  - slack
  - vagrant

mac_apps:
  - alfred
  - rectangle
