---
- name: Copy scripts to host.
  copy:
    src: "{{ item }}"
    dest: "{{ homedir }}/bin/"
    mode: 0744
    owner: "{{ username }}"
  with_fileglob:
    - bin/*

- name: Check if rust is installed
  stat: 
    path: "{{ homedir }}/.cargo/bin/cargo"
  register: cargo_stat

- name: Install rust
  block:
    - name:  Download rust installer
      get_url:
        url: "https://sh.rustup.rs"
        dest: /tmp/sh.rustup.rs
        mode: 0755
        force: true
    - name: Install Rust/Cargo
      shell: /tmp/sh.rustup.rs -y
  when: not cargo_stat.stat.exists
