---
- name: "Install packages."
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ packages }}"
  
- name: "Copy scripts to host."
  copy:
    src: "{{ item }}"
    dest: "{{ ansible_env.HOME }}/bin/"
    mode: 0744
    owner: "{{ username }}"
  with_fileglob:
    - bin/*
