---
- name: "Install ansible-pull cron job"
  cron:
    user: ansible
    name: "ansible provision"
    minute: "*/10"
    job: "/usr/bin/ansible-pull -o -U https://github.com/jhunzik/.dotfiles.git > /dev/null"

