---
- name: "Install packages."
  become: true
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ packages }}"
  tags:
    - system

- name: "Copy scripts to host."
  copy:
    src: "{{ item }}"
    dest: "/home/{{ username }}/bin/"
    mode: 0744
    owner: "{{ username }}"
  with_fileglob:
    - bin/*
  tags:
    - system
