---
- name: "Install packages."
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ apps }}"
    - "{{ packages }}"

- name: "Enable neovim repo."
  community.general.copr: 
    name: agriffis/neovim-nightly

- name: "Enable bottom repo."
  community.general.copr:
    name: atim/bottom

- name: "Configure dnf conf."
  blockinfile:
    path: /etc/dnf/dnf.conf
    block: |
      max_parallel_downloads=10
      defaultyes=True
      keepcache=True

- name: "Add dnf-plugins-core"
  dnf:
    name: dnf-plugins-core

- name: "Add repos."
  dnf:
    name:
      - "https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm"
      - "https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm"
    disable_gpg_check: true

- name: "Add hashicorp repo"
  command:
    cmd: dnf config-manager --add-repo https://rpm.releases.hashicorp.com/fedora/hashicorp.repo
    creates: /etc/yum.repos.d/hashicorp.repo

- name: "Install AppStream metadata"
  dnf:
    name: "@core"

- name: "Multimedia post install."
  dnf:
    name: "@multimedia"
    install_weak_deps: false
    exclude: PackageKit-gstreamer-plugin

- name: "Install sound-and-video complement packages."
  dnf:
    name: "@sound-and-video"

- name: "Update dnf packages."
  dnf:
    name: "*"
    state: latest

- name: "Remove fedora flathub repo."
  community.general.flatpak_remote:
    name: flathub
    state: absent

- name: "Add flathub remote repository."
  community.general.flatpak_remote:
    name: flathub-non-filtered
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo

- name: "Install Flatpack packages."
  community.general.flatpak:
    name: org.mozilla.firefox
    remote: flathub-non-filtered
