---
- name: "Update repositories."
  apt:
    update_cache: True
  changed_when: False

- name: "Install packages."
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - "{{ packages }}"
    - "{{ ubuntu_packages }}"

- name: Create Bitwarden directory
  file:
    path: /opt/bitwarden
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0755"

- name: Download Bitwarden binary
  unarchive:
    src: https://vault.bitwarden.com/download/?app=cli&platform=linux
    dest: "{{ homedir }}/bin/"
    remote_src: true
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0755"

- name: "Create fonts directory"
  file:
    path: ~/.fonts
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0755"

- name: "Install fonts"
  unarchive:
    src: "{{ item }}"
    dest: ~/.fonts
    remote_src: true
  with_items:
    - "https://download.jetbrains.com/fonts/JetBrainsMono-2.304.zip"
  notify: Update fonts cache

- name: "Install Wezterm"
  block:
    - name: Add WezTerm GPG key
      apt_key:
        url: https://apt.fury.io/wez/gpg.key
        state: present
        keyring: /usr/share/keyrings/wezterm-fury.gpg

    - name: Add WezTerm repository
      apt_repository:
        repo: 'deb [signed-by=/usr/share/keyrings/wezterm-fury.gpg] https://apt.fury.io/wez/ * *'
        state: present
        filename: wezterm

    - name: Update apt cache and install Wezterm
      apt:
        name: wezterm
        update_cache: true

    - name: Copy Wezterm config 
      copy:
        src: "wezterm"
        dest: "{{ homedir }}/.config"
        mode: 0744
        owner: "{{ username }}"
    
- include_tasks: users.yml

- include_tasks: cron.yml

- include_tasks: just.yml
