---
- name: "Update repositories."
  apt:
    update_cache: True
  changed_when: False

- name: "Install packages."
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - "{{ packages }}"
    - "{{ ubuntu_packages }}"

- name: Create Bitwarden directory
  file:
    path: /opt/bitwarden
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0755"

- name: Download Bitwarden binary
  unarchive:
    src: https://vault.bitwarden.com/download/?app=cli&platform=linux
    dest: "{{ homedir }}/bin/"
    remote_src: true
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0755"

- include_tasks: users.yml

- include_tasks: cron.yml

- include_tasks: just.yml
