---
- name: "Update repositories."
  apt:
    update_cache: True
  changed_when: False

- name: "Install packages."
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - "{{ packages }}"
    - "{{ ubuntu_packages }}"

- name:
  include_tasks:
    file: users.yml

- name:
  include_tasks:
     file: cron.yml
