---
- name: "Install packages."
  become: false
  homebrew:
    update_homebrew: true
    upgrade_all: true
    name: "{{ item }}"
    state: latest
  with_items:
    - "{{ packages }}"

- name: "Install casks."
  become: false
  homebrew_cask:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ apps }}"
    - "{{ mac_apps }}"

