---
- name: "Add neovim ppa"
  become: true
  apt_repository:
    repo: "ppa:neovim-ppa/stable"
    codename: jammy

- name: "Install packages."
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ packages }}"
    - "{{ ubuntu_packages }}"
