---
- name: "Set shell for user"
  become: true
  user:
    name: "{{ username }}"
    shell: /usr/bin/zsh

- name: "Create .zshrc"
  copy:
    src: .zshrc
    dest: "{{ ansible_env.HOME }}/.zshrc"

- name: "Install plugins"
  include_tasks: 
    file: plugins.yml
