---
- name: "Create .zshrc"
  copy:
    src: .zshrc
    dest: "{{ homedir }}/.zshrc"
    owner: "{{ username }}"
    group: "{{ username }}"

- name: "Install plugins"
  include_tasks:
    file: plugins.yml
