---
- name: "Create zsh plugins directory."
  file:
    path: "/home/{{ username }}/.zsh-plugins"
    state: directory
    mode: 0744
    owner: "{{ username }}"

- name: "Copy any additional zsh plugins."
  copy:
    src: "zsh_plugins/"
    dest: "/home/{{ username }}/.zsh-plugins/"
    mode: 0744
    owner: "{{ username }}"

- name: "Copy zsh plugin repos"
  git:
    repo: "{{ item.repo }}"
    dest: "/home/{{ username }}/.zsh-plugins/{{ item.dir }}"
    key_file: "/home/{{ username }}/.ssh/id_ed25519"
    accept_hostkey: true
  with_items:
    - { repo: "git@github.com:zsh-users/zsh-syntax-highlighting.git", dir: "zsh-syntax-highlighting" }
    - { repo: "git@github.com:zsh-users/zsh-autosuggestions.git", dir: "zsh-autosuggestions" }
    - { repo: "git@github.com:zsh-users/zsh-history-substring-search.git", dir: "zsh-history-substring-search" }
    - { repo: "git@github.com:zsh-users/zsh-completions.git", dir: "zsh-completions" }
    - { repo: "git@github.com:sindresorhus/pure.git", dir: "pure" }
