import = [
    "~/.config/alacritty/themes/themes/tokyo-night.toml"
]

live_config_reload = true

[font]
size = 16

[shell]
program = "/usr/bin/zsh"

[cursor]
style = "Block"
unfocused_hollow = true

[font.bold]
family = "Hasklug Nerd Font"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "Hasklug Nerd Font"

[font.normal]
family = "Hasklug Nerd Font"

