---
- name: "Copy tmux config."
  copy:
    src: .tmux.conf
    dest: "{{ homedir }}/.tmux.conf"
    mode: 0644

- name: "Copy tmux plugin repos"
  become_user: "{{ username }}"
  git:
    repo: "{{ item.repo }}"
    dest: "{{ homedir }}/.tmux/plugins/{{ item.dir }}"
    accept_hostkey: true
  with_items:
    - { repo: "https://github.com/tmux-plugins/tpm.git", dir: "tpm" }
    - {
        repo: "https://github.com/tmux-plugins/tmux-continuum.git",
        dir: "tmux-continuum",
      }
    - {
        repo: "https://github.com/tmux-plugins/tmux-resurrect.git",
        dir: "tmux-resurrect",
      }
