---
- name: "Download nvim tarball"
  become: true
  get_url:
    url: "https://github.com/neovim/neovim/releases/download/{{ nvim_version }}/nvim-linux64.tar.gz"
    dest: /tmp

- name: "Extract nvim binary"
  become: true
  unarchive:
    src: /tmp/nvim-linux64.tar.gz
    dest: /tmp

- name: "Copy nvim binary to user scripts"
  become: true
  copy:
    src: /tmp/nvim-linux64/bin/nvim
    dest: /usr/bin/
    mode: 0755

- name: "Create nvim autoload dir"
  file:
    path: "{{ ansible_env.HOME }}/.local/share/nvim/site/autoload/"
    state: directory

- name: "Download vimplug"
  get_url:
    url: "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
    dest: "{{ ansible_env.HOME }}/.local/share/nvim/site/autoload/"

- name: "Copy nvim conf"
  copy:
    src: init.vim
    dest: "{{ ansible_env.HOME }}/.config/nvim/"
    owner: "{{ username }}"
    mode: 0644
