---
- name: "Unzip win32yank utility"
  become: true
  unarchive:
    src: https://github.com/equalsraf/win32yank/releases/download/v0.0.4/win32yank-x64.zip
    dest: /usr/local/bin/
    remote_src: true
    mode: 0755
  when: ansible_os_family == "Debian"

- name: "Clone neovim stable branch"
  become_user: "{{ username }}"
  git:
    repo: "https://github.com/neovim/neovim"
    dest: "{{ ansible_env.HOME }}/projects/neovim"
    single_branch: true
    version: stable
    force: true
  register: update_neovim

- name: "Install neovim"
  become: true
  shell: "make CMAKE_BUILD_TYPE=RelWithDebInfo && make install"
  args:
    chdir: "{{ ansible_env.HOME }}/projects/neovim"
  when: update_neovim.changed

- name: "Copy nvim conf"
  copy:
    src: "{{ role_path }}/files/nvim/"
    dest: "{{ ansible_env.HOME }}/.config/nvim/"
    mode: 0644
    owner: "{{ username }}"

- import_tasks: plugins.yml
