---
- name: "Clone neovim stable branch"
  become_user: "{{ username }}"
  git:
    repo: "https://github.com/neovim/neovim"
    dest: "{{ homedir }}/projects/neovim"
    version: stable
    force: true
    depth: 1
  register: update_neovim

- name: "Install neovim"
  become: true
  shell: "make CMAKE_BUILD_TYPE=RelWithDebInfo && make install"
  args:
    chdir: "{{ homedir }}/projects/neovim"
  when: update_neovim.changed
  retries: 3

- name: "Copy NvChad repo"
  git:
    repo: "https://github.com/NvChad/NvChad"
    dest: "{{ homedir }}/.config/nvim"
    depth: 1
