---
- name: "Add neovim ppa"
  become: true
  apt_repository:
    repo: "ppa:neovim-ppa/stable"
    codename: jammy

- name: "install neovim"
  become: true
  package:
    name: neovim

- name: "Copy nvim conf"
  copy:
    src: "{{ role_path }}/files/nvim/"
    dest: "{{ ansible_env.HOME }}/.config/nvim/"
    mode: 0644
    owner: "{{ username }}"
