---
- name: "Unzip win32yank utility"
  become: true
  unarchive:
    src: https://github.com/equalsraf/win32yank/releases/download/v0.0.4/win32yank-x64.zip
    dest: /usr/local/bin/
    remote_src: true
    mode: 0755

- name: "Copy nvim conf"
  copy:
    src: "{{ role_path }}/files/nvim/"
    dest: "{{ ansible_env.HOME }}/.config/nvim/"
    mode: 0644
    owner: "{{ username }}"

- import_tasks: plugins.yml
