---
- name: "Install Packer NeoVim plugin manager"
  become_user: "{{ username }}"
  git:
    repo: "git@github.com:wbthomason/packer.nvim"
    dest: "/home/{{ username }}/.local/share/nvim/site/pack/packer/start/packer.nvim"
    accept_hostkey: true
