---
- name: "Install Packer NeoVim plugin manager"
  become_user: "{{ username }}"
  git:
    repo: "https://github.com/wbthomason/packer.nvim"
    dest: "{{ ansible_env.HOME }}/.local/share/nvim/site/pack/packer/start/packer.nvim"
